### ISSUE TITLE
Save file unpacking failed with wait result 258

### ISSUE THREAD

**Issue by OrbitalParallax** [pawREP/ACVIEmblemCreator#7] opened 2023-09-03 21:48 UTC
idk why this is an issue but i keep getting this error
![NVIDIA_Share_MMVqW2asvd](https://github.com/pawREP/ACVIEmblemCreator/assets/29167385/e6f2cbeb-c4bc-48ff-b905-3700e71f81c3)

**Comment by pawREP** [comment] 2023-09-04 01:28
If the reasons mentioned the error message don't apply, it's likely caused by a space character in the .sl2 file path. This issue has been partially addressed in release v1.05.

Closing as duplicate of #4

**Closed by pawREP** 2023-09-04 01:28 UTC
